/**
 * Invisible Sun — which picture belongs to which creature
 *
 * Generated by the Match Portraits window on 2026-09-13. 70 mapping(s).
 * Do not edit by hand: open that window, match there, and export again.
 *
 * This is the authoritative mapping and it ships, so a reader who imports a
 * book gets the portraits somebody already matched rather than a compendium of
 * identical icons. It works across installations because a page number is a
 * fact about the book: the importer names a book's art for the page it was
 * printed on, so the same PDF gives everyone the same file names.
 *
 * Paths are relative to the folder the importer saves art into. A mapping whose
 * file is not on disk is passed over rather than shown as a broken image, so a
 * reader who has imported none of the books simply sees the default icons.
 *
 * Anything a world sets locally wins over what is written here.
 */
export const SHIPPED_PORTRAITS = {
  "Teratology": {
    "Abdominous": "teratology/p128-1.webp",
    "Accursed Cube": "teratology/p170-1.webp",
    "Aliaska of the Forged": "teratology/p078-1.webp",
    "Ash Demon": "teratology/p120-2.webp",
    "Basil Fictorum": "teratology/p060-1.webp",
    "Cacest Spur": "teratology/p121-1.webp",
    "Captain Lazlo Melorican": "teratology/p144-1.webp",
    "Color Hound": "teratology/p155-3.webp",
    "Conflagration": "teratology/p031-2.webp",
    "Decuman": "teratology/p082-1.webp",
    "Denominator": "teratology/p162-1.webp",
    "Ekbal and the Exalted": "teratology/p083-1.webp",
    "Emel the Bodiless": "teratology/p084-1.webp",
    "Enemy of Autumn": "teratology/p172-1.webp",
    "Enemy of Health": "teratology/p173-1.webp",
    "Enemy of Property": "teratology/p174-1.webp",
    "Enescen": "teratology/p157-1.webp",
    "Ephanalisan": "teratology/p146-1.webp",
    "Esthanas, for Whom Art Is Life": "teratology/p032-1.webp",
    "Fervent": "teratology/p175-1.webp",
    "Gativa Vail, Secramal Dancer of the Third Crime": "teratology/p085-2.webp",
    "Girijda, Incomplete Prophet of the Infinite God": "teratology/p034-2.webp",
    "God of Tiny Temples": "teratology/p071-1.webp",
    "Illusine": "teratology/p043-2.webp",
    "Imition": "teratology/p103-1.webp",
    "Insangelous": "teratology/p088-1.webp",
    "J.C. Nedrick, Esquire": "teratology/p089-1.webp",
    "Kestlevarian, Wishgranter": "teratology/p147-2.webp",
    "Kollichar": "teratology/p158-1.webp",
    "Koul": "teratology/p125-1.webp",
    "Kyako": "teratology/p044-1.webp",
    "Lavansa": "teratology/p090-1.webp",
    "Legend": "teratology/p091-1.webp",
    "Mask Juggler": "teratology/p140-1.webp",
    "Melancholic Merrick": "teratology/p182-1.webp",
    "Merrusalem": "teratology/p183-1.webp",
    "Metamorphosis Queen": "teratology/p148-2.webp",
    "Miro the Enumerator": "teratology/p149-2.webp",
    "Mori Gra": "teratology/p177-1.webp",
    "Naevia, Breaker of Demons": "teratology/p165-1.webp",
    "Naomella, the Eternal Student": "teratology/p094-1.webp",
    "Nikolas the Beneficent": "teratology/p130-1.webp",
    "Niquee Criene of the Plighted Troth": "teratology/p035-1.webp",
    "Patchwork Crawler": "teratology/p112-1.webp",
    "Quorilax Cat": "teratology/p046-2.webp",
    "Reginald the Articulate": "teratology/p095-1.webp",
    "Ritika the Apostate": "teratology/p096-1.webp",
    "Semper Viven": "teratology/p057-1.webp",
    "Shadow Lamprey": "teratology/p104-1.webp",
    "Sonya of the Masks": "teratology/p151-1.webp",
    "Talliesta": "teratology/p097-1.webp",
    "Taramoc Eslin": "teratology/p098-1.webp",
    "Terre": "teratology/p161-1.webp",
    "The Archigrapher": "teratology/p080-1.webp",
    "The Frigid Sacristan": "teratology/p114-1.webp",
    "The God in the Wine Glass": "teratology/p086-1.webp",
    "The Holder of Your Keys": "teratology/p087-1.webp",
    "The Mirror Slayer": "teratology/p164-1.webp",
    "The One Who Forgets": "teratology/p166-2.webp",
    "The Seeker of Souls": "teratology/p178-1.webp",
    "The Unforgiving Clock": "teratology/p075-1.webp",
    "The Veil Child": "teratology/p099-1.webp",
    "The Vermillion Sisters": "teratology/p132-1.webp",
    "Unguis": "teratology/p029-1.webp",
    "Urchalata": "teratology/p030-1.webp",
    "Vaquith": "teratology/p167-1.webp",
    "Varuna Chikere, the Sterling": "teratology/p037-1.webp",
    "Warmonger": "teratology/p127-1.webp",
    "Watchers of the Change": "teratology/p143-1.webp",
    "Your Magnificence Caitiff Teudran (Demon)": "teratology/p133-1.webp"
  }
};
