/**
 * Invisible Sun — putting the books' pictures on the books' creatures
 *
 * The importer saves every illustration a book embeds, named for the page it
 * was printed on, and every creature knows its own page. Nothing in either says
 * which picture is which creature, and no rule written here could: the art on a
 * creature's page is as often a chapter opener or the illustration for the
 * entry facing it. So this offers the candidates, nearest page first, and a
 * person decides. See helpers/portraits.mjs for the ordering and what it is
 * worth — 141 of 307 have exactly one picture on their own page, which is a
 * good guess and not an answer.
 *
 * What it writes is a lookup table, not a portrait.
 *
 * That is the whole point of it. `toItem` sets `img` on every import, so a
 * portrait put straight onto an actor is overwritten the next time its book is
 * read — which happens often here. The table is consulted while the actors are
 * built, so an assignment survives.
 *
 * Two tables, and the order matters. The authoritative one is a file in the
 * repository, importers/portraits-data.mjs, which ships — so a reader who
 * installs this system and imports Teratology gets the portraits somebody
 * already matched rather than 307 identical icons. Over the top of it sits a
 * world setting holding only what this table has changed, so a disagreement
 * about which picture is the Abdominous can be settled without a release.
 * Export writes the shipped file's exact contents, ready to be committed.
 */
import { tableKey, groupArt, candidatesFor, allArt, progress, effectiveTable,
         toFileShape, fromFileShape, relative, resolve, presentOnly, ART_ROOT }
  from "../helpers/portraits.mjs";
import { SHIPPED_PORTRAITS } from "../importers/portraits-data.mjs";

const { ApplicationV2, HandlebarsApplicationMixin } = foundry.applications.api;

export { ART_ROOT };

/** The world setting holding the table. */
export const PORTRAIT_SETTING = "portraits";

/** Which folder under ART_ROOT each book's art went into. */
const BOOK_FOLDER = {
  "Teratology": "teratology",
  "The Path": "path",
  "The Nightside": "nightside-book"
};

/** Only what this world has changed. */
export function localTable() {
  return game.settings.get("invisible-sun", PORTRAIT_SETTING) ?? {};
}

/**
 * The mapping in force: the one that ships, with this world's corrections over
 * the top. Paths are relative to ART_ROOT — `resolve` makes one usable.
 */
export function portraitTable() {
  return effectiveTable(SHIPPED_PORTRAITS, localTable());
}

/**
 * Which of the art folders actually hold files, so a mapping naming a picture
 * this reader has not got is passed over rather than shown as a broken image.
 *
 * One browse per book, and only when something is being imported — the shipped
 * table names files that arrive with the books, and a reader who has imported
 * none of them should see default icons rather than 307 broken links.
 */
export async function artOnDisk() {
  const FP = foundry.applications.apps.FilePicker.implementation;
  const present = new Set();
  for (const folder of new Set(Object.values(BOOK_FOLDER))) {
    try {
      const listing = await FP.browse("data", `${ART_ROOT}/${folder}`);
      for (const path of listing.files) present.add(path);
    } catch { /* that book's art has not been saved */ }
  }
  return present;
}

/**
 * The portraits to use while importing, as a Map of creature name to path.
 *
 * `#writePack` already hands `toItem` an image looked up by name, which is how
 * the card decks give a card its face — so a bucket that wants portraits needs
 * nothing new, only this map.
 */
export async function portraitsFor(entries = []) {
  const table = presentOnly(portraitTable(), await artOnDisk());
  const images = new Map();
  for (const entry of entries) {
    const path = table[tableKey({ source: entry.source, name: entry.name })];
    if (path) images.set(entry.name, resolve(path));
  }
  return images;
}

/**
 * What the exported file says about itself.
 *
 * Kept here rather than copied from the file being replaced, so an export is a
 * whole file and not a fragment somebody has to paste into the middle of one.
 */
const SOURCE_HEADER = `/**
 * Invisible Sun — which picture belongs to which creature
 *
 * Generated by the Match Portraits window on {when}. {count} mapping(s).
 * Do not edit by hand: open that window, match there, and export again.
 *
 * This is the authoritative mapping and it ships, so a reader who imports a
 * book gets the portraits somebody already matched rather than a compendium of
 * identical icons. It works across installations because a page number is a
 * fact about the book: the importer names a book's art for the page it was
 * printed on, so the same PDF gives everyone the same file names.
 *
 * Paths are relative to the folder the importer saves art into. A mapping whose
 * file is not on disk is passed over rather than shown as a broken image, so a
 * reader who has imported none of the books simply sees the default icons.
 *
 * Anything a world sets locally wins over what is written here.
 */
`;

export class PortraitMatcher extends HandlebarsApplicationMixin(ApplicationV2) {

  static DEFAULT_OPTIONS = {
    id: "isun-portrait-matcher",
    classes: ["invisible-sun", "portrait-matcher"],
    tag: "div",
    position: { width: 980, height: 720 },
    window: { title: "ISUN.PortraitsTitle", icon: "fa-solid fa-image-portrait",
              resizable: true },
    actions: {
      select: PortraitMatcher.#onSelect,
      assign: PortraitMatcher.#onAssign,
      clear: PortraitMatcher.#onClear,
      "next-unassigned": PortraitMatcher.#onNextUnassigned,
      "show-all": PortraitMatcher.#onShowAll,
      "export-table": PortraitMatcher.#onExport,
      "import-table": PortraitMatcher.#onImport,
      apply: PortraitMatcher.#onApply
    }
  };

  static PARTS = {
    body: { template: "systems/invisible-sun/templates/apps/portrait-matcher.hbs" }
  };

  /** Creatures, read once: the pack index does not change while this is open. */
  #creatures = null;
  /** Art on disk, grouped by book and page. Read once for the same reason. */
  #art = null;
  #selected = null;
  #filter = "";
  /**
   * What the book says about the creature being looked at, kept once fetched.
   *
   * Not in the index. A description runs to a couple of thousand characters and
   * there are 307 of them, so asking the index for all of it would be most of a
   * megabyte read to show one paragraph. Only the creature actually selected is
   * fetched, and only the first time it is.
   */
  #details = new Map();
  /** Whether the current creature is showing its whole book rather than its page. */
  #showAll = false;

  /* The scroll positions matter more here than on a sheet: the list is 307 rows
   * and the candidates are a grid, and losing either on every click would make
   * the window unusable for the job it exists to do. */
  static SCROLLABLE = [".creature-list", ".candidate-grid"];

  _preSyncPartState(partId, newElement, priorElement, state) {
    super._preSyncPartState(partId, newElement, priorElement, state);
    for (const selector of this.constructor.SCROLLABLE) {
      const el = priorElement.querySelector(selector);
      if (el?.scrollTop) state.scrollPositions.push([selector, el.scrollTop, 0]);
    }
  }

  /** Read the pack and the art folder, once per opening. */
  async #load() {
    if (this.#creatures && this.#art) return;

    const pack = game.packs.get("invisible-sun.creatures");
    const index = pack
      ? await pack.getIndex({ fields: ["system.source", "system.page"] })
      : [];
    this.#creatures = [...index]
      .map(entry => ({
        id: entry._id,
        name: entry.name,
        source: entry.system?.source ?? "",
        book: BOOK_FOLDER[entry.system?.source] ?? "",
        page: entry.system?.page ?? null
      }))
      .sort((a, b) => a.source.localeCompare(b.source) || (a.page ?? 0) - (b.page ?? 0)
                      || a.name.localeCompare(b.name));

    /* Every book's folder, asked for separately: browse does not recurse, and
     * a book whose art was never saved should be a missing folder rather than
     * an error. */
    const FP = foundry.applications.apps.FilePicker.implementation;
    const paths = [];
    for (const folder of new Set(Object.values(BOOK_FOLDER))) {
      try {
        const listing = await FP.browse("data", `${ART_ROOT}/${folder}`);
        paths.push(...listing.files);
      } catch { /* that book's art has not been saved */ }
    }
    this.#art = groupArt(paths);
  }

  async _prepareContext() {
    await this.#load();
    const table = portraitTable();

    const filter = this.#filter.toLowerCase();
    const rows = this.#creatures
      .filter(c => !filter || c.name.toLowerCase().includes(filter))
      .map(c => ({ ...c, portrait: table[tableKey(c)] ? resolve(table[tableKey(c)]) : null }));

    const current = this.#creatures.find(c => c.id === this.#selected) ?? null;
    const candidates = !current ? []
      : (this.#showAll ? allArt(current.book, this.#art)
                       : candidatesFor(current, this.#art));

    return {
      rows,
      current: current && { ...current,
        ...(this.#details.get(current.id) ?? { description: "", traits: "", level: null }),
        portrait: table[tableKey(current)] ? resolve(table[tableKey(current)]) : null },
      candidates: candidates.map(c => ({ ...c,
        chosen: current ? resolve(table[tableKey(current)] ?? "") === c.path : false,
        // Said in words, because "why is this one being offered" is the whole
        // question a person is answering here.
        why: c.distance === null ? game.i18n.localize("ISUN.PortraitsAnywhere")
           : c.distance === 0 ? game.i18n.localize("ISUN.PortraitsSamePage")
           : game.i18n.format("ISUN.PortraitsNearPage", { page: c.page })
      })),
      showingAll: this.#showAll,
      filter: this.#filter,
      progress: progress(this.#creatures, table),
      noArt: this.#art.size === 0
    };
  }

  _onRender(context, options) {
    super._onRender(context, options);
    // Typing filters the list; a re-render on every keystroke would lose focus,
    // so the field is read here rather than being a form input the app submits.
    const search = this.element.querySelector('input[name="filter"]');
    search?.addEventListener("input", foundry.utils.debounce(event => {
      this.#filter = event.target.value;
      this.render();
    }, 250));
  }

  async #write(table) {
    await game.settings.set("invisible-sun", PORTRAIT_SETTING, table);
    this.render();
  }

  static async #onSelect(event, target) {
    this.#selected = target.closest("[data-creature-id]")?.dataset.creatureId ?? null;
    this.#showAll = false;
    await this.#describe(this.#selected);
    this.render();
  }

  /**
   * Fetch the entry's own words, once.
   *
   * A failure here is not worth stopping over: the window's job is choosing a
   * picture, and it can still be done from the name and the page if the text
   * will not come.
   */
  async #describe(id) {
    if (!id || this.#details.has(id)) return;
    try {
      const doc = await game.packs.get("invisible-sun.creatures")?.getDocument(id);
      this.#details.set(id, {
        description: doc?.system?.description ?? "",
        traits: doc?.system?.traits ?? "",
        level: doc?.system?.level ?? null
      });
    } catch (err) {
      console.warn("invisible-sun | could not read a creature's description", err);
      this.#details.set(id, { description: "", traits: "", level: null });
    }
  }

  static async #onAssign(event, target) {
    const current = this.#creatures.find(c => c.id === this.#selected);
    const path = target.closest("[data-path]")?.dataset.path;
    if (!current || !path) return;
    await this.#write({ ...localTable(), [tableKey(current)]: relative(path) });
  }

  /**
   * Take a picture off.
   *
   * Written as nothing rather than deleted. A deleted key falls through to the
   * shipped table and the picture comes straight back, which reads as the
   * control being broken; an empty one is this world saying "not that", and
   * `toFileShape` drops it on the way out so it never reaches the repository.
   */
  static async #onClear() {
    const current = this.#creatures.find(c => c.id === this.#selected);
    if (!current) return;
    await this.#write({ ...localTable(), [tableKey(current)]: "" });
  }

  /** Jump to the next creature with nothing chosen, from where we are now. */
  static async #onNextUnassigned() {
    const table = portraitTable();
    const at = this.#creatures.findIndex(c => c.id === this.#selected);
    const order = [...this.#creatures.slice(at + 1), ...this.#creatures.slice(0, at + 1)];
    const next = order.find(c => !table[tableKey(c)]);
    if (!next) return ui.notifications.info(game.i18n.localize("ISUN.PortraitsAllDone"));
    this.#selected = next.id;
    this.#showAll = false;
    await this.#describe(next.id);
    this.render();
  }

  static #onShowAll() {
    this.#showAll = !this.#showAll;
    this.render();
  }

  /**
   * The mapping as the file that ships it.
   *
   * Not a loose JSON blob: the whole of this exports so it can replace
   * module/importers/portraits-data.mjs and be committed, which is the only way
   * a match reaches anybody but the person who made it. The body is written
   * with JSON.stringify, so it is valid JSON inside a one-line export and can
   * be read back by the button beside it.
   */
  static #onExport() {
    const shape = toFileShape(portraitTable());
    const counted = Object.values(shape).reduce((n, names) => n + Object.keys(names).length, 0);
    const header = SOURCE_HEADER.replace("{count}", String(counted))
                                .replace("{when}", new Date().toISOString().slice(0, 10));
    foundry.utils.saveDataToFile(
      `${header}export const SHIPPED_PORTRAITS = ${JSON.stringify(shape, null, 2)};\n`,
      "text/javascript", "portraits-data.mjs");
  }

  static async #onImport() {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = ".mjs,.js,.json,application/json,text/javascript";
    input.addEventListener("change", async () => {
      const file = input.files?.[0];
      if (!file) return;
      try {
        /* Either what Export wrote or a bare JSON file. The exported module is
         * a comment and a single assignment whose value JSON.stringify made, so
         * the object is whatever lies between the first brace and the last. */
        const text = await file.text();
        const from = text.indexOf("{");
        const to = text.lastIndexOf("}");
        if (from === -1 || to <= from) throw new Error(game.i18n.localize("ISUN.PortraitsNoTable"));
        const shape = JSON.parse(text.slice(from, to + 1));

        /* Kept as local corrections rather than replacing the file, because
         * this window cannot write into the system folder. What it changes sits
         * over the shipped table until somebody exports and commits it. */
        const local = fromFileShape(shape);
        await this.#write(local);
        ui.notifications.info(game.i18n.format("ISUN.PortraitsImported",
          { count: Object.keys(local).length }));
      } catch (err) {
        ui.notifications.error(game.i18n.format("ISUN.PortraitsBadFile", { why: err.message }));
      }
    });
    input.click();
  }

  /**
   * Put the table onto the actors that are in the pack now.
   *
   * The next import would do this anyway, and reading three books to see a
   * portrait you just chose is not a reasonable wait. Both the sheet's picture
   * and the token's, because a creature dragged onto a scene showing the
   * default mystery-man is the half of the job nobody remembers to finish.
   */
  static async #onApply() {
    const pack = game.packs.get("invisible-sun.creatures");
    if (!pack) return;
    const table = portraitTable();

    const wasLocked = pack.locked;
    if (wasLocked) await pack.configure({ locked: false });
    try {
      const updates = [];
      for (const creature of this.#creatures) {
        const stored = table[tableKey(creature)];
        if (!stored) continue;
        const img = resolve(stored);
        updates.push({ _id: creature.id, img, "prototypeToken.texture.src": img });
      }
      if (updates.length) {
        const Cls = foundry.utils.getDocumentClass(pack.documentName);
        await Cls.updateDocuments(updates, { pack: pack.collection });
      }
      ui.notifications.info(game.i18n.format("ISUN.PortraitsApplied", { count: updates.length }));
    } finally {
      if (wasLocked) await pack.configure({ locked: true });
    }
  }
}
